# Generated by Django 3.2 on 2021-05-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='name_eng',
        ),
        migrations.AddField(
            model_name='category',
            name='name_rus',
            field=models.CharField(default='bla', max_length=100),
            preserve_default=False,
        ),
    ]
