# Generated by Django 3.2 on 2021-05-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210502_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='description_eng',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='name_eng',
        ),
        migrations.AddField(
            model_name='product',
            name='description_est',
            field=models.CharField(default='bla', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='description_rus',
            field=models.CharField(default='bla', max_length=5000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_est',
            field=models.CharField(default='bla', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='name_rus',
            field=models.CharField(default='bla', max_length=255),
            preserve_default=False,
        ),
    ]
