# Generated by Django 3.2 on 2021-05-03 07:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210502_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 19, 6, 5, 41755, tzinfo=utc)),
        ),
    ]
