# Generated by Django 3.2 on 2021-05-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210503_0736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemparameter',
            name='id',
        ),
        migrations.AlterField(
            model_name='systemparameter',
            name='key',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
