# Generated by Django 3.2 on 2021-05-03 07:53

from django.db import migrations, models
from api.constants import SystemParameterKey


def add_sysparam(apps, schema_editor):
    SystemParameter = apps.get_model("api", "SystemParameter")

    SystemParameter(
        key=SystemParameterKey.session_expiration_date_in_seconds.value,
        description='Ostukorvi säilimise aeg sekundites. Vaikimisi on 7200 sekundit ehk 2 tundi.',
        value={"value": 7200}
    ).save()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_systemparameter_description'),
    ]

    operations = [
        migrations.RunPython(add_sysparam),
    ]
