# Generated by Django 3.2 on 2021-05-03 08:11

import api.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_session_expiration_time_sysparam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemparameter',
            name='key',
            field=models.CharField(choices=[(api.constants.SystemParameterKey['session_expiration_date_in_seconds'], 'SESSION_EXPIRATION_DATE_IN_SECONDS')], max_length=100, primary_key=True, serialize=False),
        ),
    ]
