# Generated by Django 3.2 on 2021-05-03 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210503_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='expires',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
