# Generated by Django 3.2 on 2021-05-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20210503_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description_eng',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_est',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description_rus',
            field=models.TextField(blank=True, max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_eng',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_est',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='name_rus',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.TextField(max_length=255, unique=True),
        ),
    ]
