# Generated by Django 3.2.3 on 2021-05-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20210504_0956'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('BANKLINK', 'BANKLINK'), ('CARD', 'CARD'), ('CASH', 'CASH'), ('OTHER', 'OTHER')], max_length=25)),
                ('country', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('name', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
