# Generated by Django 3.2.3 on 2021-05-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210518_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttype',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos'),
        ),
    ]
