# Generated by Django 3.2.3 on 2021-07-26 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='self_pickup',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_type',
            field=models.CharField(choices=[('TOYREM_OFFICE', 'TOYREM_OFFICE'), ('ITELLA_SMARTPOST', 'ITELLA_SMARTPOST')], default='TOYREM', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='smartpost_place_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
