# Generated by Django 3.2.3 on 2021-07-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20210726_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'RECEIVED'), ('PAID', 'PAID'), ('SHIPPED', 'SHIPPED'), ('COMPLETED', 'COMPLETED')], default='RECEIVED', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
