# Generated by Django 3.2.3 on 2021-08-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_auto_20210726_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.TextField(default='asas'),
            preserve_default=False,
        ),
    ]
